from pathlib import Path
import subprocess

from ..paths import runtime_home


class NeovimError(Exception):
    pass


class NeovimAdapter:
    def __init__(
        self,
        generated_dir: Path,
    ):
        self.generated_dir = generated_dir

    def apply(
        self,
        theme: dict,
    ) -> None:
        colors = theme["colors"]

        background = colors["background"]
        surface = colors["surface"]
        foreground = colors["foreground"]
        primary = colors["primary"]
        secondary = colors["secondary"]
        accent = colors["accent"]

        theme_name = theme.get(
            "_theme_name",
            "arch-theme-manager",
        )

        self.generated_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        target = self.generated_dir / "nvim-theme.lua"

        temporary = target.with_suffix(".tmp")

        content = self._render(
            theme_name=theme_name,
            background=background,
            surface=surface,
            foreground=foreground,
            primary=primary,
            secondary=secondary,
            accent=accent,
        )

        try:
            temporary.write_text(
                content,
                encoding="utf-8",
            )

            temporary.replace(target)

        except OSError as exc:
            raise NeovimError(f"Could not generate Neovim theme: {exc}") from exc

        self._reload()

    def _render(
        self,
        *,
        theme_name: str,
        background: str,
        surface: str,
        foreground: str,
        primary: str,
        secondary: str,
        accent: str,
    ) -> str:
        return f'''-- AUTO-GENERATED - DO NOT EDIT
-- Generated by Arch Theme Manager.

local theme = {{
    name = "{theme_name}",

    background = "{background}",
    surface = "{surface}",
    foreground = "{foreground}",
    primary = "{primary}",
    secondary = "{secondary}",
    accent = "{accent}",
}}

vim.g.colors_name = "arch-theme-manager"

local function hi(
    group,
    options
)
    vim.api.nvim_set_hl(
        0,
        group,
        options
    )
end

-- ------------------------------------------------------------
-- EDITOR
-- ------------------------------------------------------------

hi("Normal", {{
    fg = theme.foreground,
    bg = theme.background,
}})

hi("NormalNC", {{
    fg = theme.foreground,
    bg = theme.background,
}})

hi("NormalFloat", {{
    fg = theme.foreground,
    bg = theme.surface,
}})

hi("FloatBorder", {{
    fg = theme.primary,
    bg = theme.surface,
}})

hi("FloatTitle", {{
    fg = theme.accent,
    bg = theme.surface,
    bold = true,
}})

hi("CursorLine", {{
    bg = theme.surface,
}})

hi("CursorColumn", {{
    bg = theme.surface,
}})

hi("ColorColumn", {{
    bg = theme.surface,
}})

hi("LineNr", {{
    fg = theme.secondary,
}})

hi("CursorLineNr", {{
    fg = theme.accent,
    bold = true,
}})

hi("SignColumn", {{
    bg = theme.background,
}})

hi("WinSeparator", {{
    fg = theme.surface,
}})

hi("VertSplit", {{
    fg = theme.surface,
}})

hi("Folded", {{
    fg = theme.secondary,
    bg = theme.surface,
}})

hi("FoldColumn", {{
    fg = theme.secondary,
    bg = theme.background,
}})

hi("EndOfBuffer", {{
    fg = theme.background,
}})

hi("NonText", {{
    fg = theme.surface,
}})

hi("Whitespace", {{
    fg = theme.surface,
}})

hi("SpecialKey", {{
    fg = theme.secondary,
}})

hi("Visual", {{
    bg = theme.surface,
}})

hi("VisualNOS", {{
    bg = theme.surface,
}})

hi("Search", {{
    fg = theme.background,
    bg = theme.primary,
    bold = true,
}})

hi("IncSearch", {{
    fg = theme.background,
    bg = theme.accent,
    bold = true,
}})

hi("CurSearch", {{
    fg = theme.background,
    bg = theme.accent,
    bold = true,
}})

hi("MatchParen", {{
    fg = theme.accent,
    bold = true,
    underline = true,
}})

-- ------------------------------------------------------------
-- MENUS / COMPLETION
-- ------------------------------------------------------------

hi("Pmenu", {{
    fg = theme.foreground,
    bg = theme.surface,
}})

hi("PmenuSel", {{
    fg = theme.background,
    bg = theme.primary,
    bold = true,
}})

hi("PmenuSbar", {{
    bg = theme.surface,
}})

hi("PmenuThumb", {{
    bg = theme.secondary,
}})

hi("WildMenu", {{
    fg = theme.background,
    bg = theme.primary,
}})

-- ------------------------------------------------------------
-- STATUS / TABS
-- ------------------------------------------------------------

hi("StatusLine", {{
    fg = theme.foreground,
    bg = theme.surface,
}})

hi("StatusLineNC", {{
    fg = theme.secondary,
    bg = theme.surface,
}})

hi("TabLine", {{
    fg = theme.secondary,
    bg = theme.surface,
}})

hi("TabLineFill", {{
    bg = theme.background,
}})

hi("TabLineSel", {{
    fg = theme.background,
    bg = theme.primary,
    bold = true,
}})

hi("WinBar", {{
    fg = theme.foreground,
    bg = theme.background,
}})

hi("WinBarNC", {{
    fg = theme.secondary,
    bg = theme.background,
}})

-- ------------------------------------------------------------
-- SYNTAX
-- ------------------------------------------------------------

hi("Comment", {{
    fg = theme.secondary,
    italic = true,
}})

hi("Constant", {{
    fg = theme.accent,
}})

hi("String", {{
    fg = theme.secondary,
}})

hi("Character", {{
    fg = theme.secondary,
}})

hi("Number", {{
    fg = theme.accent,
}})

hi("Boolean", {{
    fg = theme.accent,
    bold = true,
}})

hi("Float", {{
    fg = theme.accent,
}})

hi("Identifier", {{
    fg = theme.foreground,
}})

hi("Function", {{
    fg = theme.primary,
    bold = true,
}})

hi("Statement", {{
    fg = theme.primary,
}})

hi("Conditional", {{
    fg = theme.primary,
    italic = true,
}})

hi("Repeat", {{
    fg = theme.primary,
}})

hi("Label", {{
    fg = theme.accent,
}})

hi("Operator", {{
    fg = theme.accent,
}})

hi("Keyword", {{
    fg = theme.primary,
    italic = true,
}})

hi("Exception", {{
    fg = theme.accent,
}})

hi("PreProc", {{
    fg = theme.secondary,
}})

hi("Include", {{
    fg = theme.primary,
}})

hi("Define", {{
    fg = theme.primary,
}})

hi("Macro", {{
    fg = theme.accent,
}})

hi("PreCondit", {{
    fg = theme.secondary,
}})

hi("Type", {{
    fg = theme.secondary,
}})

hi("StorageClass", {{
    fg = theme.primary,
}})

hi("Structure", {{
    fg = theme.secondary,
}})

hi("Typedef", {{
    fg = theme.secondary,
}})

hi("Special", {{
    fg = theme.accent,
}})

hi("SpecialChar", {{
    fg = theme.accent,
}})

hi("Tag", {{
    fg = theme.primary,
}})

hi("Delimiter", {{
    fg = theme.foreground,
}})

hi("Debug", {{
    fg = theme.accent,
}})

hi("Underlined", {{
    fg = theme.secondary,
    underline = true,
}})

hi("Bold", {{
    bold = true,
}})

hi("Italic", {{
    italic = true,
}})

-- ------------------------------------------------------------
-- TREESITTER
-- ------------------------------------------------------------

hi("@comment", {{
    link = "Comment",
}})

hi("@string", {{
    link = "String",
}})

hi("@string.escape", {{
    fg = theme.accent,
}})

hi("@character", {{
    link = "Character",
}})

hi("@number", {{
    link = "Number",
}})

hi("@boolean", {{
    link = "Boolean",
}})

hi("@function", {{
    link = "Function",
}})

hi("@function.call", {{
    fg = theme.primary,
}})

hi("@function.method", {{
    fg = theme.primary,
}})

hi("@function.method.call", {{
    fg = theme.primary,
}})

hi("@constructor", {{
    fg = theme.secondary,
}})

hi("@keyword", {{
    link = "Keyword",
}})

hi("@keyword.function", {{
    fg = theme.primary,
    italic = true,
}})

hi("@keyword.return", {{
    fg = theme.primary,
    italic = true,
}})

hi("@conditional", {{
    link = "Conditional",
}})

hi("@repeat", {{
    link = "Repeat",
}})

hi("@operator", {{
    link = "Operator",
}})

hi("@type", {{
    link = "Type",
}})

hi("@type.builtin", {{
    fg = theme.secondary,
    italic = true,
}})

hi("@variable", {{
    fg = theme.foreground,
}})

hi("@variable.builtin", {{
    fg = theme.accent,
    italic = true,
}})

hi("@variable.parameter", {{
    fg = theme.secondary,
}})

hi("@property", {{
    fg = theme.secondary,
}})

hi("@field", {{
    fg = theme.secondary,
}})

hi("@constant", {{
    link = "Constant",
}})

hi("@constant.builtin", {{
    fg = theme.accent,
    bold = true,
}})

hi("@module", {{
    fg = theme.secondary,
}})

hi("@namespace", {{
    fg = theme.secondary,
}})

hi("@attribute", {{
    fg = theme.accent,
}})

hi("@tag", {{
    fg = theme.primary,
}})

hi("@tag.attribute", {{
    fg = theme.secondary,
}})

hi("@tag.delimiter", {{
    fg = theme.foreground,
}})

-- ------------------------------------------------------------
-- DIAGNOSTICS
-- ------------------------------------------------------------

hi("DiagnosticError", {{
    fg = theme.accent,
}})

hi("DiagnosticWarn", {{
    fg = theme.primary,
}})

hi("DiagnosticInfo", {{
    fg = theme.secondary,
}})

hi("DiagnosticHint", {{
    fg = theme.secondary,
}})

hi("DiagnosticOk", {{
    fg = theme.primary,
}})

hi("DiagnosticUnderlineError", {{
    sp = theme.accent,
    undercurl = true,
}})

hi("DiagnosticUnderlineWarn", {{
    sp = theme.primary,
    undercurl = true,
}})

hi("DiagnosticUnderlineInfo", {{
    sp = theme.secondary,
    undercurl = true,
}})

hi("DiagnosticUnderlineHint", {{
    sp = theme.secondary,
    undercurl = true,
}})

-- ------------------------------------------------------------
-- GIT
-- ------------------------------------------------------------

hi("DiffAdd", {{
    fg = theme.primary,
    bg = theme.surface,
}})

hi("DiffChange", {{
    fg = theme.secondary,
    bg = theme.surface,
}})

hi("DiffDelete", {{
    fg = theme.accent,
    bg = theme.surface,
}})

hi("DiffText", {{
    fg = theme.background,
    bg = theme.primary,
}})

hi("GitSignsAdd", {{
    fg = theme.primary,
}})

hi("GitSignsChange", {{
    fg = theme.secondary,
}})

hi("GitSignsDelete", {{
    fg = theme.accent,
}})

-- ------------------------------------------------------------
-- LAZYVIM / SNACKS
-- ------------------------------------------------------------

hi("SnacksNormal", {{
    fg = theme.foreground,
    bg = theme.background,
}})

hi("SnacksNormalNC", {{
    fg = theme.foreground,
    bg = theme.background,
}})

hi("SnacksPickerBorder", {{
    fg = theme.primary,
    bg = theme.surface,
}})

hi("SnacksPickerTitle", {{
    fg = theme.accent,
    bg = theme.surface,
    bold = true,
}})

hi("SnacksPickerMatch", {{
    fg = theme.accent,
    bold = true,
}})

hi("SnacksDashboardHeader", {{
    fg = theme.primary,
    bold = true,
}})

hi("SnacksDashboardKey", {{
    fg = theme.accent,
}})

hi("SnacksDashboardDesc", {{
    fg = theme.foreground,
}})

hi("SnacksDashboardIcon", {{
    fg = theme.secondary,
}})

-- ------------------------------------------------------------
-- LAZY / MASON / WHICH-KEY
-- ------------------------------------------------------------

hi("LazyButton", {{
    fg = theme.foreground,
    bg = theme.surface,
}})

hi("LazyButtonActive", {{
    fg = theme.background,
    bg = theme.primary,
    bold = true,
}})

hi("LazyH1", {{
    fg = theme.background,
    bg = theme.primary,
    bold = true,
}})

hi("MasonHeader", {{
    fg = theme.background,
    bg = theme.primary,
    bold = true,
}})

hi("MasonHighlight", {{
    fg = theme.primary,
}})

hi("WhichKey", {{
    fg = theme.primary,
}})

hi("WhichKeyGroup", {{
    fg = theme.secondary,
}})

hi("WhichKeyDesc", {{
    fg = theme.foreground,
}})

hi("WhichKeySeparator", {{
    fg = theme.surface,
}})

-- ------------------------------------------------------------
-- TERMINAL
-- ------------------------------------------------------------

vim.g.terminal_color_0 = theme.background
vim.g.terminal_color_1 = theme.accent
vim.g.terminal_color_2 = theme.primary
vim.g.terminal_color_3 = theme.secondary
vim.g.terminal_color_4 = theme.primary
vim.g.terminal_color_5 = theme.accent
vim.g.terminal_color_6 = theme.secondary
vim.g.terminal_color_7 = theme.foreground

vim.g.terminal_color_8 = theme.surface
vim.g.terminal_color_9 = theme.accent
vim.g.terminal_color_10 = theme.primary
vim.g.terminal_color_11 = theme.secondary
vim.g.terminal_color_12 = theme.primary
vim.g.terminal_color_13 = theme.accent
vim.g.terminal_color_14 = theme.secondary
vim.g.terminal_color_15 = theme.foreground

-- Let integrations inspect the current palette.
vim.g.arch_theme_manager = theme

-- Refresh the UI.
vim.cmd("redraw!")
'''

    def _reload(
        self,
    ) -> None:
        socket_dir = runtime_home() / "nvim"

        if not socket_dir.is_dir():
            return

        for socket in socket_dir.glob("*.sock"):
            result = subprocess.run(
                [
                    "nvim",
                    "--server",
                    str(socket),
                    "--remote-expr",
                    'execute("ArchThemeReload")',
                ],
                capture_output=True,
                text=True,
            )

            if result.returncode != 0:
                try:
                    socket.unlink()
                except OSError:
                    pass
